---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

###Data from Instacart users and purchases
```{r}
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(flexdashboard)
```


###Amount of products ordered from each aisle
Column {data-width=500}
-----------------------------------------------------------------------
```{r}
data("instacart")

instacart_data = instacart %>% 
  janitor::clean_names()

instacart_data %>% 
  group_by(aisle) %>%  
  summarize(amount_ordered = n()) %>% 
  plot_ly(x = ~aisle, y = ~amount_ordered, type = "scatter", mode = "markers",
          alpha = 0.5)
```


###Amount of orders by day
Column {data-width=300}
-----------------------------------------------------------------------
```{r}
instacart_data %>% 
  group_by(order_dow) %>% 
  summarize(total_orders = n()) %>% 
  plot_ly(x = ~order_dow, y = ~total_orders, type = "bar",
          alpha = 0.5)
```

###Distribution of orders by department each day
Column {data-width=300}
-----------------------------------------------------------------------
```{r}
instacart_data %>% 
  group_by(department, order_dow) %>% 
  summarize(orders = n()) %>% 
  plot_ly(x = ~order_dow, y = ~orders, type = "box", color = ~orders,
          alpha = 0.5)
```

```{r test}
# rmarkdown::render("Dashboard.Rmd", output_format = "flex_dashboard")
```



